### ISSUE TITLE
Add Footer icon in Website

### ISSUE THREAD

**Issue by RajMalik23** [RajMalik23/Hacktoberfest#16]
# My Website

This repository contains the code for my website.

## Footer Section

I've added a footer section to the website to display copyright and contact information.

### Copyright

&copy; 2023 Your Name. All Rights Reserved.

### Contact

For inquiries, you can reach out to me at info@example.com.

**Comment by adhikari-dikshant** [comment]
I can help you up with whole landing page for the hotel website, including login signup page, main home page with navbar, toggle theme, footer

**Comment by VBPMP** [comment]
please,Assign this task to me

**Comment by sooraj-gk** [comment]
Can I work on this issue? **I request you to please assign it to me.**

**Comment by RajMalik23** [comment]
Dear @adhikari-dikshant , the one who has first requested PR and followed all the Instructions given in the [readme](https://github.com/RajMalik23/Hacktoberfest/blob/main/README.md) file will be accepted first.

**Comment by adhikari-dikshant** [comment]
@RajMalik23 done

**Comment by RajMalik23** [comment]
Kudos, @adhikari-dikshant , your efforts are truly commendable!

Feel free to spread the word about this [repository](https://github.com/RajMalik23/Hacktoberfest) among your friends who are interested in contributing to open-source projects. We welcome them with open arms.

Additionally, if you have any exceptional projects to share, you can do so by creating a new issue in the repository.
