### ISSUE TITLE
Create Contact Page

### ISSUE THREAD

**Issue by RajMalik23** [RajMalik23/Hacktoberfest#2]

**Comment by Kedarnath-Rothe** [comment]
@RajMalik23 Please assign me this issue... I have worked on this issue many times so i have lots of ideas...

**Comment by AviGawande** [comment]
@RajMalik23 had worked around this task and willing to contribute if you Issue me it.

**Comment by Kedarnath-Rothe** [comment]
Hey, @RajMalik23  can i work on favicon

**Comment by RajMalik23** [comment]
@AviGawande Create a Navbar in website using Bootstrap
